In [4]:
import pandas as pd
sales = pd.read_csv('sales.csv')
sales.head()

,order_id,date,customer_id,category,region,sales,quantity,discount
0,59570135,2017-10-16,512,Одежда и обувь,Ставропольский край,1301,2,0.00
1,16578697,2017-07-18,512,Одежда и обувь,Ставропольский край,3530,4,0.05
2,46943601,2017-07-05,512,Бытовая техника,Ставропольский край,5773,1,0.10
3,42436035,2017-02-18,512,Спорт и отдых,Ставропольский край,4723,3,0.03
4,49798299,2017-09-08,512,Красота,Ставропольский край,1936,3,0.00

In [5]:
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 1554192 entries, 0 to 1554191
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   order_id     1554192 non-null  int64
 1   date         1554192 non-null  str
 2   customer_id  1554192 non-null  int64
 3   category     1554192 non-null  str
 4   region       1554192 non-null  str
 5   sales        1554192 non-null  int64
 6   quantity     1554192 non-null  int64
 7   discount     1554192 non-null  float64
dtypes: float64(1), int64(4), str(3)
memory usage: 94.9 MB

In [6]:
sales.describe()

           order_id   customer_id         sales      quantity      discount
count  1.554192e+06  1.554192e+06  1.554192e+06  1.554192e+06  1.554192e+06
mean   4.996910e+07  5.044643e+04  4.113131e+03  2.500866e+00  3.000914e-02
std    2.888088e+07  2.885639e+04  4.415475e+03  1.036733e+00  3.652684e-02
min    7.700000e+01  5.120000e+02  0.000000e+00  0.000000e+00  0.000000e+00
25%    2.494007e+07  2.545900e+04  1.136000e+03  2.000000e+00  0.000000e+00
50%    4.996420e+07  5.039800e+04  2.515000e+03  2.000000e+00  0.000000e+00
75%    7.500616e+07  7.542400e+04  5.314000e+03  3.000000e+00  5.000000e-02
max    9.999999e+07  1.005110e+05  4.200700e+04  8.000000e+00  1.000000e-01